[package]
name = "qrab_cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
qrab_encode = { path = "../qrab_encode" }
qrab_decode = { path = "../qrab_decode" }
