[package]
name = "qrab_encode"
version = "0.1.0"
edition.workspace = true

[lib]
name = "qrab_encode"

[dependencies]
qrab_core = { path = "../qrab_core" }
thiserror = { workspace = true }
bitvec = {workspace = true}
itertools = "0.13"

